[2024-12-28T14:53:21.595+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: trigger_dag_3.tsk1 manual__2024-12-28T14:53:13.331226+00:00 [queued]>
[2024-12-28T14:53:21.642+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: trigger_dag_3.tsk1 manual__2024-12-28T14:53:13.331226+00:00 [queued]>
[2024-12-28T14:53:21.642+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2024-12-28T14:53:21.642+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2024-12-28T14:53:21.643+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2024-12-28T14:53:21.679+0000] {taskinstance.py:1300} INFO - Executing <Task(BashOperator): tsk1> on 2024-12-28 14:53:13.331226+00:00
[2024-12-28T14:53:21.689+0000] {standard_task_runner.py:55} INFO - Started process 2222 to run task
[2024-12-28T14:53:21.695+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'trigger_dag_3', 'tsk1', 'manual__2024-12-28T14:53:13.331226+00:00', '--job-id', '33', '--raw', '--subdir', 'DAGS_FOLDER/triggerDag3.py', '--cfg-path', '/tmp/tmpzg4s1_a3']
[2024-12-28T14:53:21.696+0000] {standard_task_runner.py:83} INFO - Job 33: Subtask tsk1
[2024-12-28T14:53:21.833+0000] {task_command.py:388} INFO - Running <TaskInstance: trigger_dag_3.tsk1 manual__2024-12-28T14:53:13.331226+00:00 [running]> on host 2f43a4cf56a6
[2024-12-28T14:53:21.996+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=trigger_dag_3
AIRFLOW_CTX_TASK_ID=tsk1
AIRFLOW_CTX_EXECUTION_DATE=2024-12-28T14:53:13.331226+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-12-28T14:53:13.331226+00:00
[2024-12-28T14:53:21.998+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2024-12-28T14:53:21.999+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'exit 1']
[2024-12-28T14:53:22.019+0000] {subprocess.py:86} INFO - Output:
[2024-12-28T14:53:22.026+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2024-12-28T14:53:22.051+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-12-28T14:53:22.069+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=trigger_dag_3, task_id=tsk1, execution_date=20241228T145313, start_date=20241228T145321, end_date=20241228T145322
[2024-12-28T14:53:22.097+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 33 for task tsk1 (Bash command failed. The command returned a non-zero exit code 1.; 2222)
[2024-12-28T14:53:22.147+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2024-12-28T14:53:22.202+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
