[2024-12-28T14:46:24.404+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: trigger_dag_2.tsk1 manual__2024-12-28T14:46:16.810033+00:00 [queued]>
[2024-12-28T14:46:24.427+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: trigger_dag_2.tsk1 manual__2024-12-28T14:46:16.810033+00:00 [queued]>
[2024-12-28T14:46:24.427+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2024-12-28T14:46:24.428+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2024-12-28T14:46:24.428+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2024-12-28T14:46:24.459+0000] {taskinstance.py:1300} INFO - Executing <Task(BashOperator): tsk1> on 2024-12-28 14:46:16.810033+00:00
[2024-12-28T14:46:24.470+0000] {standard_task_runner.py:55} INFO - Started process 1773 to run task
[2024-12-28T14:46:24.477+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'trigger_dag_2', 'tsk1', 'manual__2024-12-28T14:46:16.810033+00:00', '--job-id', '29', '--raw', '--subdir', 'DAGS_FOLDER/triggerDag2.py', '--cfg-path', '/tmp/tmp_v00l6p_']
[2024-12-28T14:46:24.478+0000] {standard_task_runner.py:83} INFO - Job 29: Subtask tsk1
[2024-12-28T14:46:24.654+0000] {task_command.py:388} INFO - Running <TaskInstance: trigger_dag_2.tsk1 manual__2024-12-28T14:46:16.810033+00:00 [running]> on host 2f43a4cf56a6
[2024-12-28T14:46:25.017+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=trigger_dag_2
AIRFLOW_CTX_TASK_ID=tsk1
AIRFLOW_CTX_EXECUTION_DATE=2024-12-28T14:46:16.810033+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2024-12-28T14:46:16.810033+00:00
[2024-12-28T14:46:25.019+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2024-12-28T14:46:25.021+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'exit 10']
[2024-12-28T14:46:25.089+0000] {subprocess.py:86} INFO - Output:
[2024-12-28T14:46:25.097+0000] {subprocess.py:97} INFO - Command exited with return code 10
[2024-12-28T14:46:25.150+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 10.
[2024-12-28T14:46:25.180+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=trigger_dag_2, task_id=tsk1, execution_date=20241228T144616, start_date=20241228T144624, end_date=20241228T144625
[2024-12-28T14:46:25.226+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 29 for task tsk1 (Bash command failed. The command returned a non-zero exit code 10.; 1773)
[2024-12-28T14:46:25.270+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2024-12-28T14:46:25.323+0000] {taskinstance.py:2578} INFO - 1 downstream tasks scheduled from follow-on schedule check
